apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deploy-test-deployment
  labels:
    app: aks-deploy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-deploy-test
  template:
    metadata:
      labels:
        app: aks-deploy-test
    spec:
      containers:
        - name: aks-deploy-test
          image: aks-deploy-test
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aks-deploy-test-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: haks-deploy-test
  type: LoadBalancer
